TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += rotsc_0.proto
DATA += rotsc_1.proto

#=======================================
include $(TOP)/configure/RULES
