TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devrotating_sample_changer.db
DB_INSTALLS += $(TOP)/rotating_sample_changerSup/devrotating_sample_changer.proto

#=======================================
include $(TOP)/configure/RULES
